### ISSUE TITLE
保存用データ構造の設計

### ISSUE THREAD

**Issue by TakedaTakumi** [TakedaTakumi/hydrangea#3]
## ドキュメントTOML
```toml
background_color = "#fff"

[default]
inherit_style = true

	[default.node]
	text = "新しいノード"
	mergin = 10
	padding = 5
	
	[default.style]
	fill = "#fff"
	stroke = "#000"
	edge = "#000"
	
		[default.style.font]
		family = ""
		size = 14
		color = ""
		bold = false
		italic = false
		under = false

[root]
text = "新しいマップ"

	[root.right]
	id = "ulid"
	children = [
		"ulid",
	]

	[root.left]
	id = "ulid"
	children = [
		"ulid",
	]

	[root.style]
	fill = "#color"
	stroke = "#color"
	edge = "#color"
	
		[root.style.font]
		family = ""
		size = 14
		bold = false
		italic = false
		under = false

# id順にソートする
[[node_list]]
id = "#ulid"
parent_id = "#ulid"
text = ""
children = [
	"ulid",
]

	[node_list.style]
	fill = "#color"
	stroke = "#color"
	edge = "#color"
	
		[node_list.style.font]
		family = ""
		size = 14
		bold = false
		italic = false
		under = false

```

## スキーマ
https://github.com/brunoborges/toml-schema
```toml
[toml-schema]
version = "1"

[types]

	[types.ulid]
	type = "string"
	pattern = "^[0-9a-hjkmnp-zA-HJKMNP-Z]{26}$"

	[types.id_list]
	type = "collection"
	typeref = "types.ulid"

	[types.color]
	type = "string"
	pattern = "^#([0-9a-fA-F]{6})([0-9a-fA-F]{2})?$"
	
	[types.font]
	type = "table"
	
		[types.font.family]
		type = "string"
		optional = true
	
		[types.font.size]
		type = "integer"
		optional = true

		[types.font.color]
		typeref = "types.color"
		optional = true
	
		[types.font.bold]
		type = "boolean"
		optional = true
	
		[types.font.italic]
		type = "boolean"
		optional = true
	
		[types.font.under]
		type = "boolean"
		optional = true
	
	[types.default_node]
	type = "table"
	
		[types.default_node.content]
		type = "string"
		optional = true
	
		[types.default_node.mergin]
		type = "integer"
		optional = true
	
		[types.default_node.padding]
		type = "integer"
		optional = true
	
	[types.style]
	type = "table"
	
		[types.style.fill]
		typeref = "types.color"
		optional = true
	
		[types.style.stroke]
		typeref = "types.color"
		optional = true
	
		[types.style.edge]
		typeref = "types.color"
		optional = true
	
		[types.style.font]
		typeref = "types.font"
		optional = true

	[types.root_part]

		[types.root_part.id]
		typeref = "types.ulid"

		[types.root_part.children]
		typeref = "types.id_list"
		optional = true

	[types.node]
	type = "table"
	
		[types.node.id]
		typeref = "types.uuid"
	
		[types.node.parent_id]
		typeref = "types.ulid"
	
		[types.node.content]
		type = "string"

		[types.node.children]
		typeref = "types.id_list"
		optional = true
	
		[types.node.style]
		typeref = "types.style"
		optional = true

[elements]

	[elements.background_color]
	typeref = "types.color"
	optional = true
	
	[element.default]
	type = "table"
	
		[element.default.inherit_style]
		type = "boolean"
		optional = true
	
		[element.default.node]
		typeref = "types.default_node"
		optional = true
	
		[element.default.style]
		typeref = "style"
		optional = true
	
	[elements.root]
	type = "table"
	
		[elements.root.content]
		type = "string"
	
		[elements.root.right]
		typeref = "types.root_part"

		[elements.root.left]
		typeref = "types.root_part"
	
		[elements.root.style]
		typeref = "types.style"
		optional = true
	
	[elements.node_list]
	type = "collection"
	typeref = "types.node"
	optional = true

```

**Comment by TakedaTakumi** [comment]
# YAML

```yaml
background_color: "#fff"

defaults:
  node:
    content: "新しいノード"
    margin: 10
    padding: 5
  style:
    inherit_style: true
    fill: "#fff"
    stroke: "#000"
    edge: "#000"
    font:
      family: ""
      size: 14
      color: ""
      bold: false
      italic: false
      under: false

root:
  content: "新しいマップ"
  right_children:
    - "node_ulid_1"
  left_children:
    - "node_ulid_2"
  style:
    inherit_style: true
    fill: "#color"
    stroke: "#color"
    edge: "#color"
    font:
      family: ""
      size: 14
      bold: false
      italic: false
      under: false

node_list:
  "node_ulid_1":
    content: ""
    children:
      - "child_ulid_1" # このノードの子ノードのID
    style:
      inherit_style: true
      fill: "#color"
      stroke: "#color"
      edge: "#color"
      font:
        family: ""
        size: 14
        bold: false
        italic: false
        under: false
  "node_ulid_2":
    content: ""
    children:
      - "child_ulid_2" # このノードの子ノードのID
    style:
      inherit_style: true
      fill: "#color"
      stroke: "#color"
      edge: "#color"
      font:
        family: ""
        size: 14
        bold: false
        italic: false
        under: false
  # ... 他のノードも同様にリスト形式で記述
```
